/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KG7WYfehGt1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <Card className="w-full max-w-lg">
      <CardHeader>
        <div>Upload Files</div>
        <div>Choose the files you want to upload. You can select multiple files at once.</div>
      </CardHeader>
      <CardContent className="flex flex-col gap-2">
        <div className="border-dashed border rounded-lg p-4 flex items-center gap-4">
          <FileIcon className="h-6 w-6" />
          <div className="grid gap-1.5 text-sm">
            <div>example-document.pdf</div>
            <div>5.2MB</div>
          </div>
          <Button variant="ghost" size="sm">
            <XIcon className="h-4 w-4" />
            <span className="sr-only">Remove</span>
          </Button>
        </div>
        <div className="border-dashed border rounded-lg p-4 flex items-center gap-4">
          <FileIcon className="h-6 w-6" />
          <div className="grid gap-1.5 text-sm">
            <div>example-spreadsheet.xlsx</div>
            <div>1.8MB</div>
          </div>
          <Button variant="ghost" size="sm">
            <XIcon className="h-4 w-4" />
            <span className="sr-only">Remove</span>
          </Button>
        </div>
        <div className="border-dashed border rounded-lg p-4 flex items-center gap-4">
          <FileIcon className="h-6 w-6" />
          <div className="grid gap-1.5 text-sm">
            <div>example-image.jpg</div>
            <div>3.1MB</div>
          </div>
          <Button variant="ghost" size="sm">
            <XIcon className="h-4 w-4" />
            <span className="sr-only">Remove</span>
          </Button>
        </div>
        <div className="border-dashed border rounded-lg p-4 flex items-center gap-4">
          <FileIcon className="h-6 w-6" />
          <div className="grid gap-1.5 text-sm">
            <div>example-archive.zip</div>
            <div>7.6MB</div>
          </div>
          <Button variant="ghost" size="sm">
            <XIcon className="h-4 w-4" />
            <span className="sr-only">Remove</span>
          </Button>
        </div>
        <div className="border-dashed border rounded-lg p-4 flex items-center gap-4">
          <FileIcon className="h-6 w-6" />
          <div className="grid gap-1.5 text-sm">
            <div>example-code.js</div>
            <div>0.5MB</div>
          </div>
          <Button variant="ghost" size="sm">
            <XIcon className="h-4 w-4" />
            <span className="sr-only">Remove</span>
          </Button>
        </div>
        <div className="border-dashed border rounded-lg p-4 flex items-center gap-4">
          <FileIcon className="h-6 w-6" />
          <div className="grid gap-1.5 text-sm">
            <div>example-video.mp4</div>
            <div>12.4MB</div>
          </div>
          <Button variant="ghost" size="sm">
            <XIcon className="h-4 w-4" />
            <span className="sr-only">Remove</span>
          </Button>
        </div>
        <div className="border-dashed border rounded-lg p-4 flex items-center gap-4">
          <FileIcon className="h-6 w-6" />
          <div className="grid gap-1.5 text-sm">
            <div>example-presentation.pptx</div>
            <div>4.3MB</div>
          </div>
          <Button variant="ghost" size="sm">
            <XIcon className="h-4 w-4" />
            <span className="sr-only">Remove</span>
          </Button>
        </div>
        <div className="border-dashed border rounded-lg p-4 flex items-center gap-4">
          <FileIcon className="h-6 w-6" />
          <div className="grid gap-1.5 text-sm">
            <div>example-audio.mp3</div>
            <div>3.9MB</div>
          </div>
          <Button variant="ghost" size="sm">
            <XIcon className="h-4 w-4" />
            <span className="sr-only">Remove</span>
          </Button>
        </div>
        <div className="border-dashed border rounded-lg p-4 flex items-center gap-4">
          <FileIcon className="h-6 w-6" />
          <div className="grid gap-1.5 text-sm">
            <div>example-dataset.csv</div>
            <div>2.1MB</div>
          </div>
          <Button variant="ghost" size="sm">
            <XIcon className="h-4 w-4" />
            <span className="sr-only">Remove</span>
          </Button>
        </div>
      </CardContent>
      <CardFooter>
        <div className="flex justify-between w-full">
          <Button variant="outline">Cancel</Button>
          <Button>Save</Button>
        </div>
      </CardFooter>
    </Card>
  )
}

function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
